config/routes.rb
Rails.application.routes.draw do
  resources :clients
  root "clients#index"  
end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    before_action :find_client, only: [:show, :edit, :update, :destroy] 
    
    def index
        @clients =Client.all.order("last_name ASC")
    end
    
    def show
    end    


    def new
      @client = Client.new
    end
    
    def create
      @client = Client.new(client_params) 
        if @client.save 
            redirect_to root_path
        else
            render "new"
        end    
    end
    
    def edit
    end

    def update
    	if @client.update(client_params)
	        redirect_to client_path
	    else
	        render "edit"
        end         
    end

    def destroy
        @client.destroy
	    redirect_to root_path
    end
    
    
    private
    
    def client_params 
      params.require(:client).permit(:first_name, :last_name, :last_four)
    end
    
    def find_client
        @client = Client.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for @client do |f| %>
  <%= f.input :first_name,  label: "First Name" %>
  <%= f.input :last_name ,  label: "Last Name" %>
  <%= f.input :last_four ,  label: "First 4 of SSN" %>
  <%= f.button :submit %>
<% end %>

app/views/clients/_header.html.erb
 <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Client Manager</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><%= link_to "Home", root_path %></li>
                    <li><%= link_to "Home", root_path %></li>
                    <li><%= link_to "Home", root_path %></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Enter a new client", new_client_path %></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/clients/edit.html.erb
<div class="container">
<h1>Edit Client</h1>

<%= render 'form' %>
</div>

app/views/clients/index.html.erb
<div class="container">
    <h2>Listing of Clients</h2>
        <table class="table table-striped">
              <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>SSN Last 4</th>
             </tr>
         
        <% @clients.each do |client| %>
              <tr>
                <td><%= client.first_name %></td> 
                <td><%= link_to client.last_name, client_path(client) %></td> <!-- I was able to make the table column clickable with this-->
                <td><%= client.last_four %></td>
            </tr>
        <% end %>
        </table>
</div>        

app/views/clients/new.html.erb
<div class="container">
<h1>New Client</h1>

<%= render 'form' %>
</div>

app/views/clients/show.html.erb
<div class="container">
        <table class="table table-striped">
              <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>SSN Last 4</th>
             </tr>
              <tr>
                <td><%= @client.first_name %></td>
                <td><%= @client.last_name %></td>
                <td><%= @client.last_four %></td>
              </tr>
        </table>
        <%= link_to "Back", root_path %>
        <%= link_to "Edit", edit_client_path %>
        <%= link_to "Delete client", client_path(@client), method: :delete, data: { confirm: "are you want to delete this client?" }%>
</div>     

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render 'header' %>

  <%= yield %>

</body>
</html>